### ISSUE TITLE
About data

### ISSUE THREAD

**Issue by LeronQ** [rfpcordeiro/python-similarity-to-characteristic-based-forecast#1]
Hi, I'm exploring the new product forecasting project, and I  have read you code, but could't find the  new_products.xlsx and Product_Location_Update.csv in the main.py.  could you upload them? 

thanks!

**Comment by rfpcordeiro** [comment]
Hello, 

I've just uploaded two template files, one for each  you requested.

You do not need the Product_Location_Update.csv to execute, at the end of the process it is created to store the results.

**Comment by LeronQ** [comment]
OK!  I will try it 
thank you very much
